version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: recipe-postgres
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    networks:
      - recipe-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U recipe_user -d recipe_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  recipe-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: recipe-application
    environment:
      # Database configuration
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/recipe_db
      SPRING_DATASOURCE_USERNAME: recipe_user
      SPRING_DATASOURCE_PASSWORD: recipe_password

      # Flyway configuration
      SPRING_FLYWAY_URL: jdbc:postgresql://postgres:5432/recipe_db
      SPRING_FLYWAY_USER: recipe_user
      SPRING_FLYWAY_PASSWORD: recipe_password
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: true

    ports:
      - "9090:9090"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - recipe-network
    restart: unless-stopped

networks:
  recipe-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local