### GET recipes
GET http://localhost:9090/recipes

### POST carts
POST http://localhost:9090/carts

### GET carts
GET http://localhost:9090/carts/1

### POST add receipe wrong id
POST http://localhost:9090/carts/333/add_recipe
Content-Type: application/json

{
    "recipeId": 1
}

### POST add receipe wrong recipe
POST http://localhost:9090/carts/1/add_recipe
Content-Type: application/json

{
  "recipeId": 999
}

### POST add valid receipe
POST http://localhost:9090/carts/1/add_recipe
Content-Type: application/json

{
  "recipeId": 2,
  "quantity": 4
}

### DELETE invalid receipe
DELETE http://localhost:9090/carts/1/recipes/999

### DELETE receipe
DELETE http://localhost:9090/carts/1/recipes/3
